### ISSUE TITLE
Add Nextcloud 28.x compatibility

### ISSUE THREAD

**Issue by mayonezo** [nextcloud/files_retention#433]
Quick issue to update the app to support Nextcloud 28.x onwards. Thanks!

**Comment by tflidd** [comment]
There is already a stable branch for NC 28 but it is missing a release on the app store!

**Comment by Alwaysin** [comment]
Great! When can we expect that release?

**Comment by EiTiFuzzi** [comment]
> There is already a stable branch for NC 28 but it is missing a release on the app store!

Nice to know, but I'll prefer a release on the app store. Why you don't release it on the app store?

**Comment by waja** [comment]
> > There is already a stable branch for NC 28 but it is missing a release on the app store!
> 
> Nice to know, but I'll prefer a release on the app store. Why you don't release it on the app store?

Cause @tflidd is not a member of the (repository) maintainers?

**Comment by Albirew** [comment]
Came here because of error hunting
<details>
<summary>error log entry that made me come here</summary>

```
    "File": "/**RETRACTED**/apps/files_retention/lib/AppInfo/Application.php",
    "Line": 58,
    "message": "Could not boot files_retention: Call to undefined method OC\\Server::getEventDispatcher()",
    "exception": [],
    "CustomMessage": "Could not boot files_retention: Call to undefined method OC\\Server::getEventDispatcher()"
```

</details>

stable28 branch exists here, but there's no release tag, so it means it's not ready yet.

**Comment by ballerbude** [comment]
This app is absolutely essential for us, it was reckless from me not to check the compatibility before updating to NC 28. Now I have to rollback to NC 27.
I hope we'll see Support for the current NC version soon.

**Comment by Alwaysin** [comment]
I think noone is watching this repo, might be worth creating an issue at https://github.com/nextcloud/server to "bring awareness"

**Comment by martinkoerper** [comment]
@nickvergessen Sorry to bother you, but you're listed as co-maintainer for this plugin in the store.
Do you have any idea when we can expect a release here or who to contact?

**Comment by nickvergessen** [comment]
Sorry about that. It somehow slipped. I thought this was done already.

**Comment by nickvergessen** [comment]
> Now I have to rollback to NC 27.

You could have also tried to force enable the app.


But anyway 1.17.0 compatible with Nextcloud 28 is available now:
apps.nextcloud.com/apps/files_retention

**Comment by ballerbude** [comment]
> Sorry about that. It somehow slipped. I thought this was done already.

Not only Nick vergessen :)
Thanks a lot for the quick response!

**Comment by josephcsible** [comment]
> You could have also tried to force enable the app.

Doing that with the old version just resulted in a flood of errors. But it's a moot point now, because 1.17.0 works fine.

**Comment by martinkoerper** [comment]
@nickvergessen thanks a lot!

**Comment by f3k-tech** [comment]
I don't think it's fixed. I get the following message in 28.0.2:
<img width="1496" alt="Screenshot 2024-02-07 at 12 52 53" src="https://github.com/nextcloud/files_retention/assets/61347547/87bc5837-e2ff-410f-9915-e246ab1d57a3">

In 28.0.1, it was working. But the dropdown menus were only showing the first couple of tags and scrolling nor autocomplete was not working.

**Comment by jop217** [comment]
Working fine here. 
Nextcloud 28.0.2 and Retention 1.17.0

**Comment by f3k-tech** [comment]
I still have the same issue in 28.0.4.
These are my helm chart values:

```yml
image:
  flavor: fpm

nextcloud:
  host: cloud.example.com
  mail:
    enabled: true
    fromAddress: noreply.example
    domain: gmail.com
    smtp:
      host: smtp.gmail.com
      secure: ssl
      port: 465
      authtype: LOGIN
      name: noreply.example@gmail.com
      password: '******'
  configs:
    custom.config.php: |-
      <?php
      $CONFIG = array (
        'passwordsalt' => '******',
        'secret' => '******',
        'trusted_domains' => 
          array (
            0 => 'localhost',
            1 => 'cloud.example.com',
          ),
        'trusted_proxies' => 
          array (
            0 => 'traefik.traefik',
            1 => '127.0.0.1',
            2 => '10.0.0.0/8',
          ),
        'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
        'overwriteprotocol' => 'https',
        'default_phone_region' => 'NL',
        'maintenance_window_start' => 1,
        'maintenance' => false,
      );

internalDatabase:
  enabled: false

redis:
  enabled: true
  auth:
    enabled: true
    password: "******"
  global:
    storageClass: fast-ephemeral
  master:
    persistence:
      enabled: true
  replica:
    persistence:
      enabled: true

cronjob:
  enabled: true

externalDatabase:
  enabled: true
  type: mysql
  host: nextcloud-mariadb
  user: my-user-name
  password: "******"
  database: nextcloud

mariadb:
  enabled: true
  image:
    debug: true
  auth:
    database: nextcloud
    username: my-user-name
    password: "******"
    rootPassword: "******"
  architecture: standalone
  primary:
    persistence:
      enabled: true
      storageClass: "fast"
      existingClaim: data-nextcloud-mariadb-0
      accessMode: ReadWriteOnce
      size: 8Gi
    livenessProbe:
      enabled: true
    readinessProbe:
      enabled: true

persistence:
  enabled: true
  storageClass: "fast"
  existingClaim: "nextcloud-nextcloud"
  accessMode: ReadWriteOnce
  size: 20Gi
  nextcloudData:
    enabled: true
    storageClass: "slow"
    existingClaim: "nextcloud-nextcloud-data"
    accessMode: ReadWriteOnce
    size: 2000Gi

lifecycle:
  postStartCommand:
  - /bin/sh
  - -c
  - |
    update-ca-certificates;
    apt-get -y update;
    apt-get -y install ffmpeg nano bzip2;

nginx:
  enabled: true

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: cloud.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nextcloud-tls
      hosts:
        - cloud.example.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;
      rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
      rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      location = /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
        deny all;
      }
```
