### ISSUE TITLE
Cannot create new retention policy

### ISSUE THREAD

**Issue by phoropter** [nextcloud/files_retention#474]
### Steps to reproduce
1. Install retention
2. Create flow to tag files
3. Attempt to create a new retention definition

### Expected behaviour
Tell us what should happen

Tags should be scrollable past the first 5 lines

### Actual behaviour
Tell us what happens instead

Only the first 5 lines of tags can be seen, and no scrolling down the list is possible. Attempting to filter by typing does not work either.

### Server configuration
<!--
You can use the Issue Template application to prefill most of the required information: https://apps.nextcloud.com/apps/issuetemplate
-->

**Operating system**: Truenas Scale

**Web server:** Traefik

**Database:** Postgres

**PHP version:** 8.2.15

**Nextcloud version:** 28.0.2

**Where did you install Nextcloud from:**
From TrueCharts

**List of activated apps:**
<details><summary>activated apps</summary>
<p>

Enabled:                                                                                                                                                                                                                                                                                   
  - activity: 2.20.0                                                                                                                                                                                                                                                                       
  - admin_audit: 1.18.0                                                                                                                                                                                                                                                                    
  - bruteforcesettings: 2.8.0                                                                                                                                                                                                                                                              
  - calendar: 4.6.5                                                                                                                                                                                                                                                                        
  - cloud_federation_api: 1.11.0                                                                                                                                                                                                                                                           
  - comments: 1.18.0                                                                                                                                                                                                                                                                       
  - contacts: 5.5.1                                                                                                                                                                                                                                                                        
  - contactsinteraction: 1.9.0                                                                                                                                                                                                                                                             
  - cookbook: 0.11.0                                                                                                                                                                                                                                                                       
  - dashboard: 7.8.0                                                                                                                                                                                                                                                                       
  - dav: 1.29.1                                                                                                                                                                                                                                                                            
  - federatedfilesharing: 1.18.0                                      
  - federation: 1.18.0                                                
  - files: 2.0.0                                                      
  - files_automatedtagging: 1.18.0                                    
  - files_external: 1.20.0                                            
  - files_fulltextsearch: 28.0.0                                      
  - files_pdfviewer: 2.9.0                                            
  - files_reminders: 1.1.0                                            
  - files_retention: 1.17.0                                           
  - files_sharing: 1.20.0                                             
  - files_trashbin: 1.18.0                                            
  - files_versions: 1.21.0                                            
  - firstrunwizard: 2.17.0                                            
  - fulltextsearch: 28.0.0                                            
  - gpoddersync: 3.8.3                                                
  - groupfolders: 16.0.3                                              
  - holiday_calendars: 0.3.0                                          
  - logreader: 2.13.0                                                 
  - lookup_server_connector: 1.16.0                                   
  - mail: 3.5.6                                                       
  - maps: 1.3.1                                                       
  - memories: 6.2.2                                                   
  - news: 24.0.0                                                      
  - nextcloud_announcements: 1.17.0                                   
  - nextpod: 0.7.4                                                    
  - notes: 4.9.2                                                      
  - notifications: 2.16.0                                             
  - notify_push: 0.6.9                                                
  - oauth2: 1.16.3                                                    
  - oidc: 0.7.3                                                       
  - password_policy: 1.18.0                                           
  - phonetrack: 0.7.7                                                 
  - photos: 2.4.0                                                     
  - previewgenerator: 5.4.0                                           
  - privacy: 1.12.0                                                   
  - provisioning_api: 1.18.0                                          
  - recognize: 6.0.1                                                  
  - recommendations: 2.0.0                                            
  - related_resources: 1.3.0                                          
  - richdocuments: 8.3.1                                              
  - serverinfo: 1.18.0                                                
  - settings: 1.10.1                                                  
  - sharebymail: 1.18.0                                               
  - side_menu: 3.11.7                                                 
  - support: 1.11.0                                                   
  - survey_client: 1.16.0                                             
  - suspicious_login: 6.0.0                                           
  - systemtags: 1.18.0                                                
  - tasks: 0.15.0                                                     
  - text: 3.9.1                                                       
  - theming: 2.3.0                                                    
  - thesearchpage: 1.2.6                                              
  - twofactor_backupcodes: 1.17.0
  - twofactor_nextcloud_notification: 3.8.0
  - twofactor_totp: 10.0.0-beta.2
  - twofactor_webauthn: 1.3.2
  - updatenotification: 1.18.0
  - uppush: 1.4.2
  - user_saml: 6.1.1
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0-dev (installed 27.0.1)
  - encryption: 2.16.0 (installed 2.13.0)
  - user_ldap: 1.19.0

</p>
</details> 

**Nextcloud configuration:**

<details><summary>config</summary>
<p>

```xml
{                                                                                                                                                                                                                                                                                          
    "system": {                                                                                                                                                                                                                                                                            
        "memcache.local": "\\OC\\Memcache\\APCu",                                                                                                                                                                                                                                          
        "apps_paths": [                                                                                                                                                                                                                                                                    
            {                                                                                                                                                                                                                                                                              
                "path": "\/var\/www\/html\/apps",                                                                                                                                                                                                                                          
                "url": "\/apps",                                                                                                                                                                                                                                                           
                "writable": false                                                                                                                                                                                                                                                          
            },                                                                                                                                                                                                                                                                             
            {                                                                                                                                                                                                                                                                              
                "path": "\/var\/www\/html\/custom_apps",                                                                                                                                                                                                                                   
                "url": "\/custom_apps",                                                                                                                                                                                                                                                    
                "writable": true                                                                                                                                                                                                                                                           
            }                                                                                                                                                                                                                                                                              
        ],                                                                                                                                                                                                                                                                                 
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                                                                                   
        "secret": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                                                                                         
        "datadirectory": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                                                                                  
        "dbtype": "pgsql",                                                                                                                                                                                                                                                                 
        "version": "28.0.2.5",                                                                                                                                                                                                                                                             
        "overwrite.cli.url": "https:\/\/nc.domain.tld",                                                                                                                                                                                                                               
        "dbname": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                                                                                         
        "dbhost": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                                                                                         
        "dbport": "",                                                                                                                                                                                                                                                                      
        "dbtableprefix": "oc_",                                                                                                                                                                                                                                                            
        "dbuser": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                                                                                         
        "dbpassword": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                                                                                     
        "installed": true,                                                                                                                                                                                                                                                                 
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": "6379"
        },
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "upgrade.disable-web": true,
        "default_phone_region": "US",
        "share_folder": "Shared",
        "log_type": "file",
        "log_type_audit": "file",
        "loglevel": "2",
        "logfile": "\/var\/www\/html\/data\/logs\/nextcloud.log",
        "logfile_audit": "\/var\/www\/html\/data\/logs\/audit.log",
        "logdateformat": "d\/m\/Y H:i:s",
        "logtimezone": "America\/Chicago",
        "overwritehost": "nc.domain.tld",
        "overwriteprotocol": "https",
        "activity_expire_days": "90",
        "trashbin_retention_obligation": "auto",
        "versions_retention_obligation": "auto",
        "preview_imaginary_url": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": "true",
        "jpeg_quality": "60",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "preview_max_memory": "1024",
        "preview_max_filesize_image": "50",
        "onlyoffice": "",
        "maintenance": false,
        "app_install_overwrite": [
            "memories",
            "news",
            "holiday_calendars",
            "maps",
            "files_retention"
        ],
        "memories.exiftool": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "memories.gis_type": 2,
        "allow_local_remote_servers": "true",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "enforce_theme": "",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "1025",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1",
            "localhost",
            "nextcloud",
            "nextcloud-*",
            "kube.internal.healthcheck",
            "nc.domain.tld",
            "10.1.30.56",
            "nc.domain.tld\/collabora"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "enabledPreviewProviders": [
            "OC\\Preview\\Imaginary",
            "OC\\Preview\\BMP",
            "OC\\Preview\\GIF",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\Krita",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PNG",
            "OC\\Preview\\TXT",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\PDF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Movie"
        ]
    }
}
```
</p>
</details> 

### Client configuration
**Browser:** Brave & Firefox

**Operating system:** Linux

**Comment by Kryptopirat** [comment]
Same here on Version 1.17.1 with NC 28.0.2, PHP 8.2.15

**Comment by X-Raph-X** [comment]
Same here, only the first five tags of the "occ tags:list" can be used (text filter is not working at all).

![Screenshot 2024-03-28 115831](https://github.com/nextcloud/files_retention/assets/58737002/05130a1e-4c39-4c17-b2bc-5ddcd59c98b9)

![Screenshot 2024-03-28 115931](https://github.com/nextcloud/files_retention/assets/58737002/11d994bd-08eb-4eb3-b966-cf5f7d3e4a23)

Thank you for your work :-)

**Comment by f3k-tech** [comment]
I still have the same issue in 28.0.4.
These are my helm chart values:

```yml
image:
  flavor: fpm

nextcloud:
  host: cloud.example.com
  mail:
    enabled: true
    fromAddress: noreply.example
    domain: gmail.com
    smtp:
      host: smtp.gmail.com
      secure: ssl
      port: 465
      authtype: LOGIN
      name: noreply.example@gmail.com
      password: '******'
  configs:
    custom.config.php: |-
      <?php
      $CONFIG = array (
        'passwordsalt' => '******',
        'secret' => '******',
        'trusted_domains' => 
          array (
            0 => 'localhost',
            1 => 'cloud.example.com',
          ),
        'trusted_proxies' => 
          array (
            0 => 'traefik.traefik',
            1 => '127.0.0.1',
            2 => '10.0.0.0/8',
          ),
        'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
        'overwriteprotocol' => 'https',
        'default_phone_region' => 'NL',
        'maintenance_window_start' => 1,
        'maintenance' => false,
      );

internalDatabase:
  enabled: false

redis:
  enabled: true
  auth:
    enabled: true
    password: "******"
  global:
    storageClass: fast-ephemeral
  master:
    persistence:
      enabled: true
  replica:
    persistence:
      enabled: true

cronjob:
  enabled: true

externalDatabase:
  enabled: true
  type: mysql
  host: nextcloud-mariadb
  user: my-user-name
  password: "******"
  database: nextcloud

mariadb:
  enabled: true
  image:
    debug: true
  auth:
    database: nextcloud
    username: my-user-name
    password: "******"
    rootPassword: "******"
  architecture: standalone
  primary:
    persistence:
      enabled: true
      storageClass: "fast"
      existingClaim: data-nextcloud-mariadb-0
      accessMode: ReadWriteOnce
      size: 8Gi
    livenessProbe:
      enabled: true
    readinessProbe:
      enabled: true

persistence:
  enabled: true
  storageClass: "fast"
  existingClaim: "nextcloud-nextcloud"
  accessMode: ReadWriteOnce
  size: 20Gi
  nextcloudData:
    enabled: true
    storageClass: "slow"
    existingClaim: "nextcloud-nextcloud-data"
    accessMode: ReadWriteOnce
    size: 2000Gi

lifecycle:
  postStartCommand:
  - /bin/sh
  - -c
  - |
    update-ca-certificates;
    apt-get -y update;
    apt-get -y install ffmpeg nano bzip2;

nginx:
  enabled: true

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: cloud.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nextcloud-tls
      hosts:
        - cloud.example.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;
      rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
      rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      location = /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
        deny all;
      }
```
